spring:
  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/testAtaccamaDb
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    database-platform=org: hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        ddl-auto: none
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
  liquibase:
    change-log: classpath:db/liquibase/master.xml

server:
  port: 8081